### ISSUE TITLE
Proposal: Provide Z Shell auto completion file for ydcv

### ISSUE THREAD

**Issue by Firef0x** [felixonmars/ydcv#21]
Hello, @felixonmars !

Since there is no Z Shell auto completion file for `ydcv`, Z Shell would auto complete filename of the current directory by default. Then some odd auto completions are shown when using `ydcv`. Would you please provide Z Shell auto completion file for `ydcv`?

Hope for your reply! Wish you a happy Lantern Festival! :izakaya_lantern: 

Yours sincerely!

---

不小心用了中文回复了。⊙﹏⊙b 那就一直用中文吧：
- [x] 列出所有参数项

```
  -h, --help            show this help message and exit
  -f, --full            print full web reference, only the first 3 results
                        will be printed without this flag.
  -s, --simple          only show explainations. argument "-f" will not take
                        effect
  -x, --selection       show explaination of current selection.
  --color {always,auto,never}
                        colorize the output. Default to 'auto' or can be
                        'never' or 'always'.
```
- [x] 列出 `--color` 的所有可选参数
- [ ] ~~列出 `-x` 的当前选择文字~~（放弃）
- [ ] 根据输入列出搜索建议（依赖 https://github.com/felixonmars/ydcv/issues/23 ）

个人列出这些用户需求，请审阅。

**Comment by felixonmars** [comment]
I don't use zsh myself, but I'm open to a PR for this :)

**Comment by Firef0x** [comment]
好吧，我尽量试试。抱歉刚才在抢红包回复晚了。

**Comment by Firef0x** [comment]
不小心用了中文回复了。⊙﹏⊙b 那就一直用中文吧：

- [ ] 列出所有参数项

```
  -h, --help            show this help message and exit
  -f, --full            print full web reference, only the first 3 results
                        will be printed without this flag.
  -s, --simple          only show explainations. argument "-f" will not take
                        effect
  -x, --selection       show explaination of current selection.
  --color {always,auto,never}
                        colorize the output. Default to 'auto' or can be
                        'never' or 'always'.
```

- [ ] 列出 `--color` 的所有可选参数
- [ ] 列出 `-x` 的当前选择文字
- [ ] 根据输入列出搜索建议

个人列出这些用户需求，请审阅。

**Comment by felixonmars** [comment]
看起来不错. 不过 "列出 `-x` 的当前选择文字" 会不会让人误以为需要把当前选择文字作为参数? (抱歉我不太了解 zsh...)

**Comment by Firef0x** [comment]
“列出搜索建议”这一项需要 `ydcv` 提供一个参数，当增加了这个参数后， `ydcv` 把搜索建议以以下方式打印出来。（以 `--suggestions` 为例）

```sh
$ ydcv --suggestions aard

aard
aardman
aardvark
aardwolf
```

但是我不清楚怎么样调用有道词典的搜索建议 API …… :confused:

**Comment by Firef0x** [comment]
更新一下
---

“根据输入列出搜索建议”这项用户需求依赖 https://github.com/felixonmars/ydcv/issues/23 ，我想以我的能力目前还做不出来。并且考虑到如果需要不断发送网络请求的话可能会有性能问题。所以暂时搁置这项用户需求了。

这样就只剩下前面两项用户需求了，基本在 https://github.com/felixonmars/ydcv/pull/22 中实现了。我个人测试使用了近一个月（通过安装 [ydcv-git-0.3.6.20150307.cd10332-1-any.pkg.tar](https://github.com/Firef0x/ydcv/releases/download/0.3.6.20150307.cd10332/ydcv-git-0.3.6.20150307.cd10332-1-any.pkg.tar) ），没有发现有什么问题。大神如果有什么问题的话可以提出。

期待能够合并到主仓库中。
