### ISSUE TITLE
Can I use your API key directly?

### ISSUE THREAD

**Issue by WuTianming** [felixonmars/ydcv#31]
我最近给我的qq机器人程序加了个有道词典功能，是在你的代码基础上修改的（把print改成添加到字符串尾端，处理完之后发送到qq）。现在问题来了，我这人比较懒，可以直接用你的API key吗？

**Comment by felixonmars** [comment]
API Key 是有频次限制的，请求量不大没关系；如果请求量较大，建议自己申请，毕竟也只是一封邮件的事情～

**Comment by WuTianming** [comment]
哈？你这个包是传到源里给一群用户用的（而不是自用），我还以为你的API key可以无限次数使用呢（

那我还是自己申请一个吧

**Comment by felixonmars** [comment]
我这个 Key 是有限制的普通 Key 哈，大概一直能用是因为这个包没多少人用吧 <(=^_^=)>

**Comment by WuTianming** [comment]
:joy::joy:

**Comment by WuTianming** [comment]
自己申请了一个，速度还挺快，秒回呢

**Comment by WuTianming** [comment]
反正QQ群里也没那么水，每小时水不到1000次，就用这个也没啥问题

**Comment by WuTianming** [comment]
再打个广告（
[PyQBot](https://github.com/WuTianming/PyQBot)
