### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by hosiet** [felixonmars/ydcv#32]
Could you please specify under which license is the scripts released?

Thanks!

**Comment by felixonmars** [comment]
It's under GPL v3 or later. I'll add this to the repo later.

**Comment by felixonmars** [comment]
LICENSE added in master branch.

**Comment by baimafeima** [comment]
@felixonmars Could you make a new tagged release then?

**Comment by felixonmars** [comment]
@baimafeima 0.5 tagged :)
