### ISSUE TITLE
部分词语查寻异常

### ISSUE THREAD

**Issue by fanlb** [felixonmars/ydcv#48]
![ydcv](https://user-images.githubusercontent.com/6261608/50679153-31703f00-103d-11e9-980a-6bbd635ded4c.png)

[ydcv.txt](https://github.com/felixonmars/ydcv/files/2726329/ydcv.txt)

**Comment by fanlb** [comment]
![image](https://user-images.githubusercontent.com/6261608/50817859-334d4180-1360-11e9-8ec3-0b9dbf22a932.png)

**Comment by pentie** [comment]
所给例子未能复现，估计是有道API偶然抽风。

https://github.com/felixonmars/ydcv/commit/0c1c846feac5b432887af13488686410a60572b7 更新在检测查询结果不正确时， 给出提示
`Youdao API did not return correct result. errorCode: XXX`

errorCode对应的意义参照有道文档： http://ai.youdao.com/docs/doc-trans-api.s#p06
如果遇到特殊情况，请附上errorCode回复本issue。
