### ISSUE TITLE
我想添加自己的api,请问如何找到源代码文件的位置

### ISSUE THREAD

**Issue by hxse** [felixonmars/ydcv#50]
我安装的版本是 community/ydcv 0.6.2-1 (14.8 KiB 43.0 KiB) 
新手, 还请见谅

**Comment by hxse** [comment]
前段时间还能用, 今天一上发现提示
```
    Online Resource:
    * http://www.ldoceonline.com/search/?q=apple
-- No result for this query.
```
应该添加自己的api就能够解决吧

**Comment by wi24rd** [comment]
> 前段时间还能用, 今天一上发现提示
> 
> ```
>     Online Resource:
>     * http://www.ldoceonline.com/search/?q=apple
> -- No result for this query.

+1 从昨天开始出现同一问题

**Comment by zxytim** [comment]
archlinux 里在 /usr/lib/python3.7/site-packages/ydcv.py

**Comment by hxse** [comment]
多谢, 添加自己的api之后可以正常使用了

**Comment by EricDracula** [comment]
好吧，多试了几次就好了...
