### ISSUE TITLE
2019.06.30 似乎Key出错了？

### ISSUE THREAD

**Issue by Azureki** [felixonmars/ydcv#58]
> 来自您key的翻译API请求异常频繁，为保护其他用户的正常访问，只能暂时禁止您目前key的访问

**Comment by boypt** [comment]
请阅读并理解项目主页的注意事项

**Comment by Azureki** [comment]
抱歉，昨天还能用，以为是今天才失效，就没注意。

**Comment by boypt** [comment]
目前项目代码中不提供任何key，如果你的key跟他人共用，说明已经被用超限了。

Azureki <notifications@github.com> 于 2019年6月30日周日 15:45写道：
